---
version: "2.4"
services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_DB=hmdm
      - POSTGRES_PASSWORD=topsec
      - POSTGRES_USER=hmdm
    networks:
      - hmdm

  h-mdm:
    image: penguintech/h-mdm
    build: .
    ports:
      - 8080:8080
      - 31000:31000
    networks:
      - hmdm
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  hmdm: