---
- name: Template log4j hmdm
  template:
    src: templates/log4j-hmdm.j2
    dest: /opt/tomcat/work/log4j-hmdm.xml

- name: Template hmdm.xml
  template:
    src: templates/hmdm_xml.j2
    dest: /opt/tomcat/conf/Catalina/localhost/hmdm.xml

- name: Template init file
  template:
    src: templates/init1sql.j2
    dest: /opt/tomcat/work/init.sql
